import string

def myDecryptionFunction(ciphertext, keyVal):
    plaintext= ""

    for i in range(0, len(ciphertext) ):
        
        if chr(ciphertext[i]) in string.ascii_uppercase:
            
            c= ciphertext[i] - ord('A')

            p= chr(ord('A') + ((c - keyVal) % 26))
            
            plaintext += p
        else:
            print(f"The value entered: {ciphertext[i]} is not an allowable value")

    return plaintext

ciphertext= b"SROKBDSVIKMMOZDDROWYDDYDRKDQYFOBXWOXDSCLOCDGRSMRQYFOBXCVOKCDKXNSCRYEVNVSUODYCOOSDKMDONEZDYWYBOBKZSNVIKXNCICDOWKDSMKVVIMKBBSONYEDSDPSXKVVIKWYEXDCDYDRSCGRSMRKVCYSLOVSOFODRKDQYFOBXWOXDSCLOCDGRSMRQYFOBXCXYDKDKVVKXNGROXWOXKBOZBOZKBONPYBSDDRKDGSVVLODROUSXNYPQYFOBXWOXDGRSMRDROIGSVVRKFOQYFOBXWOXDSCKDLOCDLEDKXOHZONSOXDLEDWYCDQYFOBXWOXDCKBOECEKVVIKXNKVVQYFOBXWOXDCKBOCYWODSWOCSXOHZONSOXDDROYLTOMDSYXCGRSMRRKFOLOOXLBYEQRDKQKSXCDKCDKXNSXQKBWIKXNDROIKBOWKXIKXNGOSQRDIKXNNOCOBFODYZBOFKSVWKIKVCYKDVKCDLOLBYEQRDKQKSXCDKCDKXNSXQQYFOBXWOXDDROCDKXNSXQKBWISCYXVIKXKBWYPDROCDKXNSXQQYFOBXWOXDDROQYFOBXWOXDSDCOVPGRSMRSCYXVIDROWYNOGRSMRDROZOYZVORKFOMRYCOXDYOHOMEDODROSBGSVVSCOAEKVVIVSKLVODYLOKLECONKXNZOBFOBDONLOPYBODROZOYZVOMKXKMDDRBYEQRSDGSDXOCCDROZBOCOXDWOHSMKXGKBDROGYBUYPMYWZKBKDSFOVIKPOGSXNSFSNEKVCECSXQDROCDKXNSXQQYFOBXWOXDKCDROSBDYYVPYBSXDROYEDCODDROZOYZVOGYEVNXYDRKFOMYXCOXDONDYDRSCWOKCEBOMCOPSFOPYEBDRBOO"
keyVal= 10 #K has a numeric value of 10

plaintext= myDecryptionFunction(ciphertext, keyVal)
print(plaintext)